# This one fixes one component to the same as LLL
## IF the LLL has a (... 1, ...) somewhere

beru to tak, že mám >tries< matic, které mají někde v LLLku jedničku a na té jedničce to zkoušim

In [2]:
# from closest_vs_minimal import shortest_lc_in_cube
# from copy import deepcopy
%run closest_versus_minimal_tools.ipynb

In [3]:
# UNINTERESTING TOOLS
from random import randint, seed

def shortestVector(matrix): 
    """
    :returns: 
        - n - norm of the shortest vector
        - v - the shortest vector (vector)
        - i - index of the SV
    """
    return sorted([(matrix[idx].norm().n(), matrix[idx], idx) for idx in range(matrix.nrows())])[0][1]

def randomMatrix(dimension, per) -> matrix:
    '''
    Returns a random square matrix with full rank.
    INPUT:
    dimension: dimension of the random matrix
    per: perimeter of the components
    '''
    list = [randint(-per, per) for _ in range(dimension**2)]
    M = matrix(ZZ, dimension, dimension, list)
    while M.rank() != dimension:
        list = [randint(-per, per) for _ in range(dimension**2)]
        M = matrix(ZZ, dimension, dimension, list)
    return M

def gram_matrix(matrix) -> matrix:
    return matrix * matrix.transpose()

def matrix_to_list(A) -> list:
    return [[int(A.list()[row * A.ncols() + col]) for col in range(A.ncols())] for row in range(A.nrows())]

def vector_to_list(vector) -> list:
    return [float(num) for num in vector.list()]

### Interesting math tools. 

Following functions actually have some thoughts behind them. 


`abnormality_data`
Given a matrix $B$ and it's shortest vector given by the LLL algorithm, returns __a dictionary__ with data concerting the SV given by the cube algorithm, if it's far enough from the LLL solution. 

`find_real_minimum` Given a matrix $B$ and it's shortest vector given by the LLL algorithm, returns the __linear combination of the SV given by the cube algorithm__.




### Formatting tools

These functions provide transfering the data to the output jsonfile as described above.

In [4]:
### output formatting
import json
import numpy as np

def format_data(output_data):
    for dic in output_data:
        for key, value in dic.items():
            if isinstance(value, sage.matrix.matrix_integer_dense.Matrix_integer_dense):
                dic[key] = matrix_to_list(value)
            elif isinstance(value, (int, float, sage.rings.real_mpfr.RealNumber)):
                dic[key] = float(value) 
            else:
                dic[key] = vector_to_list(value)
    return output_data

    
def into_json(data, jsonfilename):
    with open(jsonfilename, 'w') as f:
        json.dump(data, f)

def from_json(filename):
    out_file = open(filename)
    return json.load(out_file)

def print_listdict(list) -> None:
    """
    :param list: list of dictionaries
    """
    for dictionary in list:
        for pair in dictionary.items():
            print(pair[1], ": ", pair[0])
        print()

def norm_G(lin_comb, Gram_matrix):
    tmp = [sum(x * y for x, y in zip(lin_comb, col)) for col in zip(*Gram_matrix)]
    return sum(x * y for x, y in zip(tmp, lin_comb))
    
def into_dict(B, lcLLL: vector, lcCube: int, lc_exact) -> dict:
    result = {}
    G = gram_matrix(B)
    lc_shortest_in_cube=  vector(shortest_lc_in_cube(lcCube, B))
    result["B"] = B
    result["G"] = G
    result["lincomb_exact"] = lc_exact
    result["lincomb_LLL"] = lcLLL
    result["lincomb_cube"] = lcCube
    result["lincomb_cube_shortest"] = lc_shortest_in_cube
    result["exact.norm"] = vector(lc_exact*B).norm().n(digits=5)
    result["LLL.norm"] = vector(lcLLL*B).norm().n(digits=5)
    result["shortest_cube.norm"] = (vector(lc_shortest_in_cube)*B).norm().n(digits=5)
    result["sv_LLL"] = lcLLL * B
    result["sv_exact"] = lc_exact * B
    result["sv_shortst_cube"] = lc_shortest_in_cube* B
    return result

### Main function

This cell actually generates the new examples and checks wheter a matrix is *dysfunctional*. 

`generate_new_examples`
The main function. Based on input parameters above, generates *some* number of *dysfunctional* matrices, computes their invariants such as Gram matrix, LLL/cube linear combinations etc. and creates a json file with this information (specified above).

`is_dysfunctional`
Given a matrix $B$, checks whether its dysfunctional and if so, returns the data describing the case.


In [24]:
# MAIN 
from sage.modules.free_module_integer import IntegerLattice


def generate_new_examples(iterations, dimension, perimeter, jsonfilename, printing = False, functioning = True) -> None:
    '''
    generates >iterations< of >dis/functioning< matrices and saves them in a json file.
    returns number of suitable cases
    '''
    output_data = []
    i = 0
    # for i in range(iterations):
    while i < iterations:
        B = randomMatrix(dimension, perimeter)
        G = gram_matrix(B)

        L = IntegerLattice(B, lll_reduce=False)

        sv_LLL = shortestVector(B.LLL())
        lcLLL = B.solve_left(sv_LLL)

        sv_exact = L.shortest_vector()
        lc_exact = B.solve_left(sv_exact)
        sv_exact_norm = sv_exact.norm().n()

        if 1 not in lc_exact.list():
            continue


        # Compare the result with solution of the cube algorithm
        this_case_works, lcCube = compare_with_cube(lc_exact, G)
        if this_case_works != functioning:
            case_info = into_dict(B, lcLLL, lcCube, lc_exact)
            output_data.append(case_info)
        i +=1
    
    # Format output data
    if printing: print_listdict(output_data)
    dict = format_data(output_data)
    into_json(dict, jsonfilename)
    return len(output_data)


def find_indices(lst, targets):
    return [i for i, x in enumerate(lst) if x in targets]


def compare_with_cube(lc_exact, G) -> bool:
    working_case = None
    for current_row in find_indices(lc_exact, [1,-1]):
        # for K in range(2, rng):
        exact_component = lc_exact[current_row]
        lcCube = find_real_minimum(G, current_row, exact_component)
        working_case = lcCube                

        # if norm_G(lcCube, G) > norm_G(lc_exact, G):
        #     # print("cube bigger than LLL")
        # Check for invalid cases
        if norm_G(lcCube, G) > norm_G(lc_exact, G) or lcCube == zero_vector(SR, dimension):
            continue

        # Check if the two results are the same
        for i in range(dimension - 1):  
            difference = abs(lc_exact[i]) - abs(lcCube[i])
            if abs(difference) >= sensitivity:
                return True, lcCube
    return False, working_case
        
def find_real_minimum(G, current_row, unit_component) -> vector:
    """
    returns linear combination of the minimum over real numbers
    the >current_row< parameter is the coordinate of fixed col/row idk
    the >K< parameter is the number inserted into this column
    LLL component is +- 1
    """
    matrixA = matrix(dimension - 1, dimension - 1, 0) # square matrix of size (dimension - 1) x (dimension - 1), filled with zeros.
    matrixB = matrix(dimension - 1, 1, 0) # column matrix of size (dimension - 1) x 1, filled with zeros.
    matrixA[0,0] = 1
    a, b = 0, 0
    for row in range(dimension):
        if row != current_row:
            matrixA[a] = [G[row, j] for j in range(len(G[row])) if j != current_row]
            matrixB[b] = sum([unit_component * G[row,j] for j in range(len(G[row])) if j == current_row])
            a += 1
            b += 1
    # insert indices
    result = (matrixA.solve_right((-1)*unit_component * matrixB)).list()
    result.insert(current_row, unit_component)
    return vector(result).n(digits=5)

In [45]:
dimension = 10

perimeter = 1000
sensitivity = 1
tries = 100
# jsonfilename = "basic_cube_nonf_matrices_%sx%s_%s_tries_%s_perimeter.json"% (dimension, dimension, tries ,perimeter)
jsonfilename = "functioning-true-dim-10-randomperimeter-1000.json"
generate_new_examples(tries, dimension, perimeter, jsonfilename, printing=True, functioning=True)

[ 810 -314 -408  507  348  386  995 -944  718  866]
[ 289  284  873  247 -307 -576 -929 -943 -532   38]
[-911 -828  908 -840  724 -205 -586  872 -802  692]
[  97 -144 -381  213 -289 -987  392 -277 -383  152]
[ 949  178  129 -973 -433  696 -561  -11  -45 -418]
[ 580 -300  129  765   90 -561  914 -275  324 -708]
[ 946   62 -192 -990  864  -89 -926  545  671  437]
[ 493  403 -174 -442 -743 -182  -71   75  282 -250]
[ 997 -382 -602  322  738 -249 -154  836  599 -848]
[-274  840  597   53 -240 -529 -699  603  275  904] :  B
[ 4594950  -798444 -2484242   413837  -657282  1502531    13886  -364599   250398 -1274542]
[ -798444  3450098   157643   470945   468732  -109555  -329175   164496 -1345683  1040824]
[-2484242   157643  5837618  -559810  -467655 -2150471  1170041 -1362299 -1071688  1326783]
[  413837   470945  -559810  1678551 -1014958   943708  -921263   161685  -168107  -181179]
[ -657282   468732  -467655 -1014958  3059151  -888475  1711866  1273074   399042  -354067]
[ 1502531  -109

60